config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  resources :promotions do
    member do
    post 'generate_coupons'
    post 'approve'
    end  
    get 'search', on: :collection
  end
  resources :coupons, only: [] do
    post 'disable', on: :member
  end
  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :coupons, only: [:show], param: :code
    end
  end
  resources :product_categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, disabled: 10 }
  delegate :discount_rate, to: :promotion

  def as_json(options = {})
    super({ methods: :discount_rate }.merge(options))
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :user
  has_many :coupons
  has_one :promotion_approval
  has_one :approver, through: :promotion_approval, source: :user

  validates :name, :code, :discount_rate,
            :coupon_quantity, :expiration_date, presence: true
  validates :code, :name, uniqueness: true
  SEARCHABLE_FIELDS = %w[name code description].freeze

  def generate_coupons!
    return if coupons.any?

    (1..coupon_quantity).each do |number|
      coupons.create!(code: "#{code}-#{'%04d' % number}")
    end
  end

  # TODO: Fazer testes para esse método
  def coupons?
    coupons.any?
  end

  scope :search, lambda { |query|
    where(
      SEARCHABLE_FIELDS
        .map { |field| "#{field} LIKE :query" }
        .join(' OR '),
      query: "%#{query}%"
    )
      .limit(5)
  }

  scope :available, -> { where('expiration_date >= ?', Time.zone.now) }

  def self.search(query)
    where(
      SEARCHABLE_FIELDS
        .map { |field| "#{field} LIKE :query" }
        .join(' OR '),
      query: "%#{query}%"
    )
      .limit(5)
  end

  def approved?
    promotion_approval.present?
  end

  def can_approve?(current_user)
    user != current_user
  end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :promotions, dependent: :destroy
  has_many :promotion_approvals, dependent: :nullify
  has_many :approved_promotions, through: :promotion_approvals, source: :promotion
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  respond_to :json
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_error

  private

  def not_found_error
    head 404
  end
end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < Api::V1::ApiController
  def show
    @coupon = Coupon.active.find_by!(code: params[:code])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def disable
    @coupon = Coupon.find(params[:id])
    @coupon.disabled!
    redirect_to @coupon.promotion, notice: t('.success', code: @coupon.code)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  def index
    @product_category = ProductCategory.all
  end

  def show
    @product_category = ProductCategory.find(params[:id])
  end

  def new
    @product_category = ProductCategory.new
  end

  def create
    @product_category = ProductCategory.new(product_params)
    if @product_category.save
      redirect_to @product_category
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product_category).permit(:name, :code)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[generate_coupons show edit destroy update approve]
  before_action :can_be_approved, only: [:approve]

  def index
    @promotions = Promotion.all
  end

  def show; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = current_user.promotions.new(promotion_params)
    if @promotion.save
      redirect_to @promotion, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    return redirect_to @promotion, notice: t('.success') if @promotion.update(promotion_params)

    render :edit
  end

  def destroy
    if @promotion.destroy
      redirect_to promotions_path, notice: t('.exclude')
    else
      render :index
    end
  end

  def generate_coupons
    @promotion.generate_coupons!
    redirect_to @promotion, notice: t('.success')
  end

  def search
    @term = params[:q]
    @promotions = Promotion.search(@term)
  end

  def approve
    current_user.promotion_approvals.create!(promotion: @promotion)
    PromotionMailer.with(promotion: @promotion, user: @user).approval_email.deliver_now
    redirect_to @promotion, notice: 'Promoção aprovada com sucesso'
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :expiration_date, :description,
              :discount_rate, :code, :coupon_quantity)
  end

  def can_be_approved
    unless @promotion.can_approve?(current_user)
      redirect_to @promotion,
                  alert: 'Ação não permitida'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_categorys_helper.rb
module ProductCategorysHelper
end

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3>Boas vindas ao sistema de gestão de promoções</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Promoção</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <p><%= link_to 'Home', root_path %></p>
      <% if user_signed_in? %>
        <%= current_user.email %>
        <%= link_to 'Sair', '#' %>
        <%= link_to 'Promoções' , promotions_path %>
        <%= link_to 'Produtos' , product_categories_path %>
      <% else %>
        <%= link_to 'Cadastrar', new_user_registration_path %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>
    </nav>
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/product_categories/index.html.erb
<h1>Lista de Categorias de Produtos</h1>
<% if @product_category.empty? %>
  <h2>Não existe nenhum produto cadastrado</h2>
<% end %>
<table>
  <thead>
    <tr>
      <td>Nome do Produto</td>
    </tr>
    <tbody>
      <% @product_category.each do |product|%>
        <tr>
          <td>
            <%= product.name %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>

app/views/product_categories/new.html.erb
<h1>Cadastrar um Produto </h1>
<%= form_with model: @product_category, local:true do |form|%>
  <div>
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name%>
  </div>
  <div>
    <%= form.label :code, 'Código' %>
    <%= form.text_field :code %>
  </div>
  <%= form.submit "Criar produto" %>
<% end %>

app/views/product_categories/show.html.erb
<p>
  <%= link_to 'Voltar', product_categories_path %>
</p>
<h3>Detalhes do Produto</h3>
<p>
  <strong>Nome do Produto</strong>
  <%= @product_category.name %>
</p>
<p>
  <strong>Nome do Produto</strong>
  <%= @product_category.code %>
</p>

app/views/promotions/_promotion.html.erb
<h3><%= link_to promotion.name, promotion %></h3>
<dl>
  <dt><%= Promotion.human_attribute_name(:description) %></dt>
  <dd><%= promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name(:discount_rate) %></dt>
  <dd><%= number_to_percentage promotion.discount_rate, separator: ',', precision: 2 %></dd>
</dl>
<%= link_to 'Apagar', promotion, method: :delete %>

app/views/promotions/edit.html.erb
<h1>Editando promoção </h1>
<% if @promotion.errors.any? %>
  <h4>Encontramos erro, promoção não foi atualizada</h4>
  <ul>
    <% @promotion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @promotion, local: true do |form|%>
  <div>
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name%>
  </div>
  <div>
    <%= form.label :description, 'Descrição' %>
    <%= form.text_field :description%>
  </div>
  <div>
    <%= form.label :code, 'Código' %>
    <%= form.text_field :code%>
  </div>
  <div>
    <%= form.label :discount_rate, 'Desconto' %>
    <%= form.number_field :discount_rate, in: 10..90, step: 5 %>
  </div>
  <div>
    <%= form.label :coupon_quantity, 'Quantidade de cupons' %>
    <%= form.number_field :coupon_quantity%>
  </div>
  <div>
    <%= form.label :expiration_date, 'Data de término' %>
    <%= form.text_field :expiration_date %>
  </div>
  <%= form.submit "Atualizar promoção" %>
<% end %>

app/views/promotions/index.html.erb
<%= link_to 'Voltar', root_path %>
<%= link_to 'Registrar uma promoção', new_promotion_path %>
<%= form_with url: search_promotions_path, local: true, method: :get do |f| %>
<%= f.label :q, 'Busca' %>
<%= f.text_field :q %>
<%= f.submit 'Buscar'%>
<% end %>
<% if @promotions.empty?%>
  <h3> Nenhuma promoção cadastrada</h3>
<% end %>

<%= render @promotions %>

app/views/promotions/new.html.erb
<h1>Registrar uma promoção </h1>
<% if @promotion.errors.any? %>
  <h4>Encontramos erro, promoção não foi salva</h4>
  <ul>
    <% @promotion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @promotion, local: true do |form|%>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>
  <div>
    <%= form.label :discount_rate %>
    <%= form.number_field :discount_rate, in: 10..90, step: 5 %>
  </div>
  <div>
    <%= form.label :coupon_quantity %>
    <%= form.number_field :coupon_quantity %>
  </div>
  <div>
    <%= form.label :expiration_date %>
    <%= form.text_field :expiration_date %>
  </div>
  <%= form.submit %>
<% end %>

app/views/promotions/search.html.erb
<%= link_to 'Voltar', root_path %>
<%= link_to 'Registrar uma promoção', new_promotion_path %>
<%= form_with url: search_promotions_path, local: true, method: :get do |f| %>
  <%= f.label :q, 'Busca' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>
<%= t '.result', count: @promotions.count, term: @term %>
<%= render @promotions %>

app/views/promotions/show.html.erb
 <%= link_to 'Voltar', promotions_path %>
<h3> <%= @promotion.name %></h3>
<dl>
  <dt><%= Promotion.human_attribute_name :description %></dt>
  <dd><%= @promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name :discount_rate %></dt>
  <dd><%= number_to_percentage(@promotion.discount_rate, precision: 2 ) %></dd>
  <dt><%= Promotion.human_attribute_name :code %></dt>
  <dd><%= @promotion.code %></dd>
  <dt><%= Promotion.human_attribute_name :expiration_date %></dt>
  <dd><%= @promotion.expiration_date%></dd>
  <dt><%= Promotion.human_attribute_name :coupon_quantity %></dt>
  <dd><%= @promotion.coupon_quantity %></dd>
</dl>
<% if @promotion.approved? %>
  <p>Aprovada por: <%= @promotion.approver.email %></p>
<% if @promotion.coupons.empty? %>
  <%= button_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion) %>
<% end %>
<% elsif @promotion.can_approve?(current_user) %> 
  <%= link_to 'Aprovar', approve_promotion_path(@promotion), method: :post, data: {confirm: 'Tem Certeza? pois não poderá desfazer.'} %>
<% end %>

<% @promotion.coupons.each do |coupon|%>
  <div id="coupon-<%= coupon.code.parameterize %>">
    <p><%= coupon.code %> (<%= Coupon.human_attribute_name("status.#{coupon.status}")%>)</p>
    <% if coupon.active? %>
      <%= link_to 'Desabilitar', disable_coupon_path(coupon), method: :post, data: { disable_with: 'Estamos desabilitando.....'} %>
    <% end %>
  </div>
<% end %>